### PR TITLE
Fix route nans

### PR DESCRIPTION
**Pull request by pb-nowa**
Add ternaries and refactor the render function inside of the Info component, so that "NAN" no longer shows up when route data doesn't exist on the Route page. 
#169 
Screen Shot 2019-07-24 at 10 43 21 AM
Screen Shot 2019-07-24 at 10 43 34 AM

### CODE REVIEW

**Comment by hathix** [comment]
I can go through this with you. Terence probably knows the most and can give you a more thorough review. Looks good at a first glance.

**Comment by hathix** [comment]
@exxonvaldez just told me that the backend has changed so your approach may not work. Ask him how he did it.

**Comment by pb-nowa** [comment]
edit: keeping the "Performance by Time of Day" chart as per Terence

**Comment by pb-nowa** [comment]
I tried to compare the changes inside the Info Component, but a lot of it has moved around. So any help with resolving those merge conflicts is much appreciated.

**Comment by hathix** [comment]
Anyone want to help Preston with the merge conflicts? @exxonvaldez or @youngj or @akgupta89?

**Comment by akgupta89** [comment]
> Anyone want to help Preston with the merge conflicts? @exxonvaldez or @youngj or @akgupta89?

All the changes he committed to the Info and MapSpider were done by the auto formatter, so I just disregarded them with the version in master since they were out of date.

Ready for review.

**Comment by akgupta89** [comment]
> So I think the NaNs are back for this test case (14R in the late evening) because the way the back end is representing "no data" has changed. So instead of headwayMin being null, it now comes back non-null and empty.
> Screen Shot 2019-08-14 at 8 32 07 PM

I hope I didn't remove some code of his, which I fear I may have. There were a bunch of changes. I suggest rebasing your local branch with master @pb-nowa or just create a new fresh branch off master and apply the changes. Hopefully all these formatting issues are resolved when my branch gets the linting and formatting up to standard.

**Comment by hathix** [comment]
Going to consider this abandoned

**Pull request closed without merging**
