### PR TITLE
Serverless Frontend Builds

### PR DESCRIPTION
**Pull request by akgupta89**
## Proposed changes
- Create environment file for prod build setting BASE_URL
- Example hosted here: https://akgupta89.github.io/frontend/build/index.html

## Todo
- Setup Github Actions to build and deploy to S3 Bucket or Github Pages
- Bake `js_config` into frontend builds? Possible if we decouple any agency / computed dynamic data into a predictable format?

## Future Concerns
- Support different frontend consumption schemes? GraphQL vs Raw Data Dumps (Optimized Backend vs Serverless Backend)

### CODE REVIEW

**Comment by hathix** [comment]
Arun, you said you got this working, right? Are there code changes that require an updated PR?

**Comment by hathix** [comment]
Hey Arun, any updates here?

**Comment by akgupta89** [comment]
I'll need to double check, but I believe the build changes are done. I'd need an S3 bucket to deploy to which is configured for serverless builds and the API key, and set up a github actions script to build and deploy to there. @EddyIonescu

**Comment by hathix** [comment]
Running into this GraphQL issue when I run your branch, but not others. Is this related to what you said in the Slack chat?

```
metrics-flask-dev | 172.18.0.1 - - [05/Jun/2020 12:38:25] "GET /api/js_config HTTP/1.1" 200 -
metrics-flask-dev | An error occurred while resolving field DirectionIntervalMetrics.averageSpeed
metrics-flask-dev | Traceback (most recent call last):
metrics-flask-dev |   File "/usr/local/lib/python3.7/site-packages/graphql/execution/executor.py", line 450, in resolve_or_error
metrics-flask-dev |     return executor.execute(resolve_fn, source, info, **args)
metrics-flask-dev |   File "/usr/local/lib/python3.7/site-packages/graphql/execution/executors/sync.py", line 16, in execute
metrics-flask-dev |     return fn(*args, **kwargs)
metrics-flask-dev |   File "/app/backend/models/schema.py", line 498, in resolve_averageSpeed
metrics-flask-dev |     return round_or_none(dir_metrics.get_average_speed(units, scheduled=False))
metrics-flask-dev |   File "/app/backend/models/metrics.py", line 565, in get_average_speed
metrics-flask-dev |     raise Exception("Missing stop geometry")
metrics-flask-dev | Exception: Missing stop geometry
metrics-flask-dev | Traceback (most recent call last):
metrics-flask-dev |   File "/usr/local/lib/python3.7/site-packages/graphql/execution/executor.py", line 450, in resolve_or_error
metrics-flask-dev |     return executor.execute(resolve_fn, source, info, **args)
metrics-flask-dev |   File "/usr/local/lib/python3.7/site-packages/graphql/execution/executors/sync.py", line 16, in execute
metrics-flask-dev |     return fn(*args, **kwargs)
metrics-flask-dev |   File "/app/backend/models/schema.py", line 498, in resolve_averageSpeed
metrics-flask-dev |     return round_or_none(dir_metrics.get_average_speed(units, scheduled=False))
metrics-flask-dev |   File "/app/backend/models/metrics.py", line 565, in get_average_speed
metrics-flask-dev |     raise Exception("Missing stop geometry")
metrics-flask-dev | graphql.error.located_error.GraphQLLocatedError: Missing stop geometry
metrics-flask-dev |
metrics-flask-dev | An error occurred while resolving field DirectionIntervalMetrics.averageSpeed
metrics-flask-dev | Traceback (most recent call last):
metrics-flask-dev |   File "/usr/local/lib/python3.7/site-packages/graphql/execution/executor.py", line 450, in resolve_or_error
metrics-flask-dev |     return executor.execute(resolve_fn, source, info, **args)
metrics-flask-dev |   File "/usr/local/lib/python3.7/site-packages/graphql/execution/executors/sync.py", line 16, in execute
metrics-flask-dev |     return fn(*args, **kwargs)
metrics-flask-dev |   File "/app/backend/models/schema.py", line 498, in resolve_averageSpeed
metrics-flask-dev |     return round_or_none(dir_metrics.get_average_speed(units, scheduled=False))
metrics-flask-dev |   File "/app/backend/models/metrics.py", line 565, in get_average_speed
metrics-flask-dev |     raise Exception("Missing stop geometry")
metrics-flask-dev | Exception: Missing stop geometry
metrics-flask-dev | 172.18.0.1 - - [05/Jun/2020 12:38:27] "GET /api/graphql?query=query($agencyId:String!,+$routeId:String!,+$dates:[String!],+$startTime:String,+$endTime:String)+%7B+agency(agencyId:$agencyId)+%7B+route(routeId:$routeId)+%7B+interval(dates:$dates,+startTime:$startTime,+endTime:$endTime)+%7B+directions+%7B+directionId+segments+%7B+fromStopId+toStopId+medianTripTime+trips+%7D+cumulativeSegments+%7B+fromStopId+toStopId+medianTripTime+trips+%7D+%7D+%7D+%7D+%7D+%7D&variables=%7B%22agencyId%22:%22muni%22,%22routeId%22:%228%22,%22dates%22:[%222020-06-04%22],%22startTime%22:null,%22endTime%22:null%7D HTTP/1.1" 200 -
metrics-flask-dev | Traceback (most recent call last):
metrics-flask-dev |   File "/usr/local/lib/python3.7/site-packages/graphql/execution/executor.py", line 450, in resolve_or_error
metrics-flask-dev |     return executor.execute(resolve_fn, source, info, **args)
metrics-flask-dev |   File "/usr/local/lib/python3.7/site-packages/graphql/execution/executors/sync.py", line 16, in execute
metrics-flask-dev |     return fn(*args, **kwargs)
metrics-flask-dev |   File "/app/backend/models/schema.py", line 498, in resolve_averageSpeed
metrics-flask-dev |     return round_or_none(dir_metrics.get_average_speed(units, scheduled=False))
metrics-flask-dev |   File "/app/backend/models/metrics.py", line 565, in get_average_speed
metrics-flask-dev |     raise Exception("Missing stop geometry")
metrics-flask-dev | graphql.error.located_error.GraphQLLocatedError: Missing stop geometry
metrics-flask-dev |
metrics-flask-dev | 172.18.0.1 - - [05/Jun/2020 12:38:27] "GET /api/graphql?query=query($agencyId:String!,+$dates:[String!],+$startTime:String,+$endTime:String)+%7B+agency(agencyId:$agencyId)+%7B+agencyId+interval(dates:$dates,+startTime:$startTime,+endTime:$endTime)+%7B+routes+%7B+routeId+directions+%7B+directionId+medianWaitTime+averageSpeed(units:%22mph%22)+travelTimeVariability+onTimeRate+%7D+%7D+%7D+%7D+%7D&variables=%7B%22agencyId%22:%22muni%22,%22dates%22:[%222020-06-04%22],%22startTime%22:null,%22endTime%22:null%7D HTTP/1.1" 200 -
```

**Comment by hathix** [comment]
Eddy, let me know once you've done the required setup and we can merge this.

**Pull request merged**
