### PR TITLE
RouteTable:  use filled Chips with light background colors and add units

### PR DESCRIPTION
**Pull request by exxonvaldez**
Related to #429.

## Proposed changes

Color table cells with metric values (wait, speed, etc.) by quartile.  Add units (min, mph) to each cell's value.

## Screenshot

Screen Shot 2019-11-20 at 3 46 24 PM

## Link to demo, if any

http://wpg-opentransit.herokuapp.com

### CODE REVIEW

**Comment by hathix** [comment]
What are our thoughts on the "pill" solution that Terence mentioned on Slack? Looks better than the heavy colors this currently uses.

Screen Shot 2019-11-23 at 11 46 24 PM

**Comment by exxonvaldez** [comment]
> What are our thoughts on the "pill" solution that we mentioned on Slack? Looks better than the heavy colors this currently uses.

- Pills seem to be much better received than cell backgrounds colors and text colors, so we can set aside the other options, and I can update this PR to be pills for people to try out.
- The hues still need some attention on differentiation.  There is a lime and an amber (for 2nd best and 3rd best quartiles) that look a bit too similar to me.
- If we go with these new hues, then should trying carrying them over to the cards on the route summary and trip summary.
- I think it's better with units, can revisit dropping units after we try a fixed table header (still might want units even then).

**Comment by exxonvaldez** [comment]
I forgot that the colors automatically carry over to the other cards because they use the same function for colors.

Updated this PR as follows:

Switched from background cell colors to filled Chips.  Removed table row borders, added custom padding.

I made the lime and green backgrounds slightly darker than in the first Chip screenshot.

I also made the text color for the route and trip summary match the Material UI default (black with alpha of 0.87, as opposed to just solid black).  This change is imperceptible unless you know to look for it.

Updated route table:

Screen Shot 2019-11-25 at 1 10 30 PM

Route summary:

Screen Shot 2019-11-25 at 1 12 01 PM


Trip summary:

Screen Shot 2019-11-25 at 1 12 19 PM

**Comment by exxonvaldez** [comment]
Removed table header units (except "Long Wait %", as that one didn't seem to work without the percent sign):

Screen Shot 2019-11-25 at 11 55 03 PM

**Comment by exxonvaldez** [comment]
With headers scooted over to align with columns, which have extra padding due to chips.  Need some feedback on this and the potential issues I mentioned earlier.

Screen Shot 2019-11-26 at 12 01 43 AM

**Comment by youngj** [comment]
What do you think about making some of the background colors a bit darker? I think it might not be as clear how the very light background colors rank from good to bad.

Using `range([red[200], amber[200], lime[200], green[100]])`:

image

**Comment by exxonvaldez** [comment]
> What do you think about making some of the background colors a bit darker? I think it might not be as clear how the very light background colors rank from good to bad.
> 
> Using `range([red[200], amber[200], lime[200], green[100]])`


Yeah, that's a good point.  Going darker makes the colors punchier and easier to distinguish.  I tried a few iterations, and realized that going down to three colors made differentiation a lot easier and allowed for less punchy colors.  I think this why traffic maps from Google and Waze use green/yellow/red/dark red, and why I copied that for our speed colors, because any four color scheme was too complicated.

How about this one?  [red[200], red[50], yellow[100], green[50]]

Screen Shot 2019-11-27 at 12 54 50 AM

(The built in colors don't include a rust or dark red.  There is brown that wasn't close enough to red).

One thing I should mention is that using color alone to convey information is an accessibility no-no.  We'll need affordances for color blind users, like some other layer that conveys the same information (perhaps toggleable by user preference), such as a background texture, font weight or decoration, or a border pattern (like the partial circles), or small horizontal bars.  Ideally it'd be something that can be left on and help all users differentiate.

**Comment by exxonvaldez** [comment]
Here's another three hue variant with two shades of green:  [red[100], yellow[100], green[100], green[200]]

Screen Shot 2019-11-27 at 10 24 34 AM

**Comment by hathix** [comment]
You can merge this if you like -- just file an issue for making a color blind-friendly adjustment to the chips. Trello does it well, I think:

Screen Shot 2019-12-04 at 4 51 10 PM

**Comment by hathix** [comment]
Can we use this color scheme with chips?

image

**Comment by hathix** [comment]
Other ways to add patterns: show multiple dots (1-4 based on how good/bad), vary the outline width, etc. 

But I think making this color blind friendly is its own issue...

**Comment by hathix** [comment]
We could also use different color boldnesses to make sure the colors stand out. Ideally you would want the chips to look clearly distinct even if viewed in grayscale.

**Comment by exxonvaldez** [comment]
Okay, the SF team was good with going full circle back to the current colors with chips:  [red[300], yellow[300], lightGreen[700], green[900]].  The lightGreen was lightened from 800 to 700 to make things a little more distinguishable on the monochromatic scale.  Seanny has red-green color blindness of some kind, and the more intense colors are easier for him to distinguish.

I'm sure we'll revisit this again soon.

Screen Shot 2019-12-05 at 12 05 47 AM

**Pull request merged**
