### PR TITLE
Add title to dashboard, isochrone, and routesScreen pages

### LINKED ISSUE #384: Update page <title> to match route
Currently, the page <title> (thing you see in the tab bar) always says "OpenTransit". We should update the title to say descriptive info about the page you're seeing.

For instance, https://muni.opentransit.city/route/L/direction/L____I_F00/fromStop/5726/toStop/5417 could say "L Train Inbound from Church St Station Inbound to  Powell Station Inbound | OpenTransit".

### PR DESCRIPTION
**Pull request by mwpark2014**
Fixes #384 

## Proposed changes
Add title to dashboard, isochrone, and route screen pages. 
Title will change to route name, destination, and start/end stop when route loads. 
...

## Screenshot
image
image
image
...

## Testing
Manually testing the title for dashboard, isochrone, and routes pages. 
Manually testing different routes to make sure there is no regression in top left route title for null values
...

### CODE REVIEW

**Comment by mwpark2014** [comment]
As an FYI, I'm still planning on making changes to both of my open PRs. Combination of holiday events and being sick leading to delays...

**Comment by exxonvaldez** [comment]
Good to know, thanks!

**Comment by hathix** [comment]
@mwpark2014, can you pick this back up?

**Comment by mwpark2014** [comment]
@hathix yup, I'm going to pick it back up - it's been... a very busy past month for me, sorry!

**Comment by mwpark2014** [comment]
Trying to update and clear out my PRs. Sorry for the huge delay.

Here's the update for this PR:
I switched to using a titleReducer as you mentioned. I struggled a bit with figuring out how to dynamically create the title for the `Routes` page. I basically wanted to update the title state with the result of the backend request for start/end stop. I attempted a couple things (I already forgot what they were) including moving the call around, but I didn't end up getting it to work. In the interest of closing out this particular PR, I updated the titles statically. Let's get this merged and someone can iterate upon that. 

And the update for my involvement with OpenTransit:
I've always thought that if I were to actively contribute to this project, I would want to commit to a minimum level of involvement. I was trying to clear out my other commitments, but I unfortunately wasn't able to. Things kept coming up these past couple of months and work ended up taking up all my attention, so I plan to drop off until my schedule clears up. Apologies for the delay and best of luck!

**Comment by mwpark2014** [comment]
I'm getting this error in my dev environment. It doesn't _seem_ relevant to my changes... seems pretty innocuous too. When I comment the imported components from `react-select`, everything seems to work as expected. I haven't touched this project in 2 months, so I have no idea when my dev setup broke

```
./src/components/ReactSelect.jsx
Module not found: Can't resolve 'react-select' in '/app/frontend/src/components'
```

**Comment by exxonvaldez** [comment]
> I'm getting this error in my dev environment. It doesn't _seem_ relevant to my changes... seems pretty innocuous too. When I comment the imported components from `react-select`, everything seems to work as expected. I haven't touched this project in 2 months, so I have no idea when my dev setup broke
> 
> ```
> ./src/components/ReactSelect.jsx
> Module not found: Can't resolve 'react-select' in '/app/frontend/src/components'
> ```

Do a “docker-compose build” to pick up the new dependency.  Then rerun docker-compose up.

**Comment by mwpark2014** [comment]
> Do a “docker-compose build” to pick up the new dependency. Then rerun docker-compose up.

> Step 4/7 : RUN cd /app/frontend && npm install
>  ---> Running in af2aadcbaec5
> npm WARN registry Unexpected warning for https://registry.npmjs.org/: Miscellaneous Warning EAI_AGAIN: request to https://registry.npmjs.org/qs failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org registry.npmjs.org:443
> npm WARN registry Using stale data from https://registry.npmjs.org/ due to a request error during revalidation.
> npm ERR! code EAI_AGAIN
> npm ERR! errno EAI_AGAIN
> npm ERR! request to https://registry.npmjs.org/@material-ui%2fstyles failed, reason: getaddrinfo EAI_AGAIN registry.npmjs.org registry.npmjs.org:443
> 
> npm ERR! A complete log of this run can be found in:
> npm ERR!     /root/.npm/_logs/2020-03-02T06_33_28_138Z-debug.log
> ERROR: Service 'react-dev' failed to build: The command '/bin/sh -c cd /app/frontend && npm install' returned a non-zero code: 1

Yikes

**Comment by exxonvaldez** [comment]
Hmm, looks like something going on with the containers:  https://github.com/StefanScherer/dockerfiles-windows/issues/270 . Have not seen that before.

**Comment by exxonvaldez** [comment]
Hey Mason, thanks for getting the title reducer started, and sorry you have to drop off.  Changes looks good.  There is an opportunity to refactor the metadata for our UI pages, as info form is distributed across:

- the page reducer (page.js) for root-component-per-page type names
- routes map (mapRoutes.js) for url paths
- SidebarButton.jsx for names in the navigation, and 
- here in the title reducer for titles.

I'll create a new issues for that.

**Pull request merged**
