### PR TITLE
Weird line spacing on stats tiles fix

### LINKED ISSUE #436: Fix weird line spacing on stats tiles
The line spacing on the tiles (see "Typical Journey") is pretty wide, making the tile look weird when the text wraps. Can we reduce that?

Screen Shot 2019-11-20 at 8 00 51 PM

### PR DESCRIPTION
**Pull request by mwpark2014**
Fixes #436

## Proposed changes
Fix the line spacing styling so that there isn't a blank link when title wraps. 
While I was changing up things, I moved styles from in-line to css-in-js declared at the top for best practices (more consistent, group all styling rules together, avoid in-line styling) and passed in a common style into `InfoTripSummary`
...

## Screenshot
image
image

...

## Testing
I just manually tested for desktop and smaller screens. I'm not aware of any tests. It would probably be good to have an imagediff/snapshot test at some point when things are stable
...
Seems like there could be a component created for the two cards that is _not_ `InfoScoreCard` but shares some core look and feel, but I considered that out of scope for this bug.

### CODE REVIEW

**Comment by hathix** [comment]
This one has been sitting around for a while now. Anyone care to pick it up?

**Comment by mwpark2014** [comment]
Could you give me another week and someone can pick this up if I don't get to it by then? I've been really busy in January and it's been hard to justify working on this over other work, but if this is higher priority than minor, I'll pick this up again this weekend

**Comment by hathix** [comment]
Sure, of course. Take your time!

**Comment by mwpark2014** [comment]
As per https://github.com/trynmaps/metrics-mvp/pull/467#issuecomment-593227700, 
someone can go ahead and pick this up since I'm just dragging my feet on this.

Seems like there are some pretty significant merge conflicts and I won't be able to get around to fixing

**Comment by hathix** [comment]
Terence's new Google Analytics-like UI is going to remove the need for this since the cards will be wider and the text won't wrap. I'll mark this as not needed then...

**Pull request closed without merging**
