### PR TITLE
[WIP] Replaced yarn with NPM

### PR DESCRIPTION
**Pull request by akgupta89**
Tested NPM vs Yarn
_Please do not merge this yet_

using NPM and disabling package auditing, the service starts up in ~45s (checks for deprecated/audited packages which needs to be skipped) 
using yarn, the service starts up in ~40s

There are a lot of pro NPM articles if you search for NPM vs Yarn 2019, but I don't know if there is any valuable metrics behind this. I think we should discuss this more before deciding on one or the other and possibly merging this PR

Other factors to consider:
* Package install time
* Future of tooling: 
  * Yarn: https://github.com/yarnpkg/yarn/issues/6953

Addressing task: https://trello.com/c/96kHqsAa/139-remove-all-yarn-usage-make-it-npm-instead

### CODE REVIEW

**Comment by hathix** [comment]
naming this as a WIP so we don't accidentally merge

**Comment by hathix** [comment]
Let us know once you're ready for review Arun!

**Comment by sravanti** [comment]
Thanks for doing this benchmarking! It seems like from your analysis that NPM is faster, which IMO is fine to switch to, since I don't believe there are huge differences between NPM and Yarn. Looking through the future plans for yarn, I don't see anything that would significantly improve our workflow. For a MVP, I think you have the right idea that we should optimize for speed/developer experience.

One note of caution: I wouldn't suggest skipping package auditing—we don't want to download malicious versions of packages, which auditing would prevent.

**Comment by akgupta89** [comment]
Updated my original post. It seems that they perform relatively the same, both in start time and downloading packages time so essentially its up in the air in regards to personal choice

**Comment by akgupta89** [comment]
> Thanks for doing this benchmarking! It seems like from your analysis that NPM is faster, which IMO is fine to switch to, since I don't believe there are huge differences between NPM and Yarn. Looking through the future plans for yarn, I don't see anything that would significantly improve our workflow. For a MVP, I think you have the right idea that we should optimize for speed/developer experience.
> 
> One note of caution: I wouldn't suggest skipping package auditing—we don't want to download malicious versions of packages, which auditing would prevent.

Correct me if I'm wrong, but yarn doesn't audit every time it starts up, this check has to be run manually. That was the decision behind disabling auditing is to get a fair comparison between npm and yarn. I feel like that is a command that should be done manually, especially if yarn isn't doing the same and it adds significant delay to the start up time.

**Comment by hathix** [comment]
I'm fine with just going with NPM if it's a roughly equivalent experience.

**Comment by hathix** [comment]
Arun, is this ready to merge?

**Comment by akgupta89** [comment]
> Looks good to me as long as you can confirm that this builds and runs properly.

Works fine, just tested. Ready to be merged.

**Pull request merged**
