### PR TITLE
Editchart

### PR DESCRIPTION
**Pull request by fruit13ok**
I tried out the 'react-d3-components' change chart color, tick format with %, build-in axis label, but the build-in axis label is in the inside of the chart so I wrap it with a div and put another label outside.

### CODE REVIEW

**Comment by sravanti** [comment]
Thank you so much for doing this! Can you include a screenshot of what your changes look like? :)

**Comment by fruit13ok** [comment]
Hi Sravanti,

I added an identical bar chart on top of original bart chart wrap in div
and I added Info.css file.
I highlighted change on the new bart chart in green color and listed out on
the right side.

thank you,
Yi
[image: Screen Shot 2019-04-13 at 11.31.18 AM.png]

**Comment by sravanti** [comment]
Ah, looks like your screenshot didn't load, mind trying again? I'm sure your changes look fine, just want to get approval from a few members of the team before we merge. Thanks!

**Comment by fruit13ok** [comment]
attached again

**Comment by sravanti** [comment]
Can you go directly into the GitHub interface and attach? It's not working through email. Thanks!

**Comment by fruit13ok** [comment]
Screen Shot 2019-04-13 at 11 31 18 AM

**Comment by fruit13ok** [comment]
I directly attached the edited chart image onto Github.
https://github.com/trynmaps/metrics-mvp/pull/69

**Comment by sravanti** [comment]
Sorry I'm just now replying to this! Looks great, thanks for the work here :) I think after you fix the merge conflict this should be good to go! Let me know if you need help resolving the merge conflict and I can help out. Thanks!

**Comment by fruit13ok** [comment]
> Sorry I'm just now replying to this! Looks great, thanks for the work here :) I think after you fix the merge conflict this should be good to go! Let me know if you need help resolving the merge conflict and I can help out. Thanks!

I will fit it Wednesday, I am still working on my take home small projects from my last job interview.

**Comment by hathix** [comment]
Abandoned, Yi is going on #82 instead

**Pull request closed without merging**
